export const mockData = [
  {
    id: 1,
    number: 22,
    created_at: '2025-01-10T14:56:08.091Z',
    controlled_at: '2025-01-12T14:56:08.091Z',
    completed_at: null,
    system: 'СКУД',
    type: 'Неисправность',
    address: {
      name: 'Административное здание',
      city: 'Минск',
      street: 'Кирова',
      placement: 5,
    },
    request_text:
      'Центральный вход. Датчик L1: Датчик L1 на центральном входе здания не функционирует должным образом. Требуется диагностика и ремонт для восстановления его работоспособности.',
    status: ['В работе'],
    technological: true,
    files: ['https://example.com/files/image1_thumbnail.jpg', 'https://example.com/files/image2_thumbnail.jpg'],
  },
  {
    id: 2,
    number: 23,
    created_at: '2025-01-11T10:30:00.000Z',
    controlled_at: '2025-01-13T10:30:00.000Z',
    completed_at: null,
    system: 'СКУД',
    type: 'Неисправность',
    address: {
      name: 'Спортивный комплекс',
      city: 'Молодечно',
      street: 'Невский проспект',
      placement: 5,
    },
    request_text:
      'Провести техническое обслуживание оборудования: Необходимо провести плановое техническое обслуживание всего оборудования в соответствии с установленными регламентами и инструкциями для обеспечения его надёжной работы.',
    status: ['Просрочена'],
    technological: false,
    files: ['https://example.com/files/image3_thumbnail.jpg'],
  },
  {
    id: 3,
    number: 24,
    created_at: '2025-01-12T09:15:45.000Z',
    controlled_at: '2025-01-14T09:15:45.000Z',
    completed_at: '2025-01-16T09:15:45.000Z',
    system: 'СКУД',
    type: 'Неисправность',
    address: {
      name: 'Библиотека',
      city: 'Брест',
      street: 'Ленина',
      placement: null,
    },
    request_text:
      'Не работает система контроля доступа: Система контроля доступа в здании перестала функционировать. Требуется провести диагностику и устранение неисправности для восстановления нормальной работы системы.',
    status: ['Выполнена'],
    technological: true,
    files: [],
  },
  {
    id: 4,
    number: 25,
    created_at: '2025-01-12T09:15:45.000Z',
    controlled_at: '2025-01-12T10:15:45.000Z',
    completed_at: null,
    system: 'Камера',
    type: 'Неисправность',
    address: {
      name: 'Библиотека',
      city: 'Гомель',
      street: 'Ленина',
      placement: 15,
    },
    request_text:
      'Необходимо отремонтировать камеру: Одна из камер видеонаблюдения вышла из строя. Требуется ремонт или замена камеры для возобновления полного обзора и мониторинга территории.',
    status: ['Есть отзыв'],
    technological: true,
    files: [],
  },
  {
    id: 5,
    number: 27,
    created_at: '2025-01-10T14:56:08.091Z',
    controlled_at: '2025-01-12T14:56:08.091Z',
    completed_at: null,
    system: 'СКУД',
    type: 'Неисправность',
    address: {
      name: 'Здание администрации',
      city: 'Минск',
      street: 'Кирова',
      placement: 5,
    },
    request_text:
      'Фронтальный периметр. Датчик Ultrasonic: Датчик Ultrasonic на фронтальном периметре перестал работать. Необходимо провести диагностику и ремонт для восстановления его функциональности и обеспечения безопасности периметра.',
    status: ['В работе'],
    technological: true,
    files: ['https://example.com/files/image1_thumbnail.jpg', 'https://example.com/files/image2_thumbnail.jpg'],
  },
  {
    id: 6,
    number: 29,
    created_at: '2025-01-12T09:15:45.000Z',
    controlled_at: '2025-01-12T10:15:45.000Z',
    completed_at: '2025-01-12T19:16:45.000Z',
    system: 'Камера',
    type: 'Неисправность',
    address: {
      name: 'Библиотека',
      city: 'Гомель',
      street: 'Ленина',
      placement: 15,
    },
    request_text:
      'Необходимо отремонтировать камеру: Одна из камер видеонаблюдения вышла из строя. Требуется ремонт или замена камеры для возобновления полного обзора и мониторинга территории.',
    status: ['Выполнена'],
    technological: true,
    files: [],
  },
];
